default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  schema_search_path: rideshare

test:
  <<: *default
  url: postgresql://postgres:@localhost/rideshare_test

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: rideshare_development
  variables:
    statement_timeout: 5000
